# Generated by Django 4.0.2 on 2022-02-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_employee_remove_chat_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.organization'),
        ),
    ]
